- name: Manage Real Madrid Team
  hosts: FIFA_Teams
  gather_facts: no
  vars:
    manager_name: "Carlo Ancelotti"
  tasks:
    - name: Apply template to create a manager file
      template:
        src: Manager_RM.j2
        dest: /tmp/RealMadridManager.txt

    - name: Display manager file content
      command: cat /tmp/RealMadridManager.txt
      register: output

    - name: Show manager info
      debug:
        msg: "{{ output.stdout }}"